#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>

#include "build/create_c_fileConfig.h"
#include "file_to_buf.h"

#define FILE_NAME_SIZE 100
typedef struct{
  char * name;
} arena;

#define CASE_DIFFERENCE 'a' - 'A'

void strtoupper (char * str)
{
  while(*str)
  {
    if (*str >= 'a' && *str <= 'z')
    {
      *str -= CASE_DIFFERENCE;
    }
    str++;
  }
}

void validateProjectName (arena * program_arena)
{
  char bad_chars[] = {'/', '@', '#', '|', '&', '$', '{', '}', '[', ']', '(', ')', '*'};

  unsigned int num_bad_chars = sizeof(bad_chars);

  for (unsigned int i = 0; i < num_bad_chars; i++)
  {
    char * BCloc = strchr(program_arena->name, bad_chars[i]);
    if (BCloc)
    {
      printf("\
ERROR: \"%c\" is not a permitted character to use as part of a name for a project\n\
generated by this program. Characters not permitted to be used are:\n\n",
bad_chars[i]);

      for (unsigned int j = 0; j < num_bad_chars; j++)
      {
        printf("%c ", bad_chars[j]);
      }

      putc('\n', stdout);
      fflush(stdout);
      exit(EXIT_FAILURE);
    }
  }
}

void printHelp()
{
  puts("Requires one argument as input, the name of the C file,\n\
which is used to name the accompanying header.");
}

void parseCLI(arena * a, int argc, char ** argv)
{
  if (argc == 1)
  {
    printHelp();
    exit(EXIT_FAILURE);
  }

  for (int i = 1; i < argc; i++)
  {
    if(!strcmp("-h", argv[i]) || !strcmp("--h", argv[i]) || !strcmp("--help", argv[i]))
    {
      printHelp();
      exit(EXIT_SUCCESS);
    }
    else
    {
      a->name = argv[i];
    }
  }
}

void genCFile(arena * a)
{
  char * suffix = ".c";
  size_t suffix_len = strlen(suffix);

  size_t name_len = strlen(a->name);
  char filename[FILE_NAME_SIZE];

  if (suffix_len + name_len > FILE_NAME_SIZE)
  {
    printf("File name of %s is too long. Max file name size is %zu. Exiting\n",
           a->name,
           FILE_NAME_SIZE - suffix_len);
    exit(EXIT_FAILURE);
  }

  strcpy(filename, a->name);
  strcat(filename, suffix);
  #define C_SOURCE_FILE ASSET_DIR "source_file.txt" 
  FILE * source_fp = fopen(C_SOURCE_FILE, "r");
  assert(source_fp);
  FILE * dest_fp = fopen(filename, "w");
  assert(dest_fp);

  buffer buf;
  buf.buf_size = BUF_SIZE;
  buf.buf = calloc(1, BUF_SIZE);
  copyFileToBuf(&buf, source_fp);
  fprintf(dest_fp, buf.buf, NULL /*to shut up compiler warnings*/);  
  fclose(source_fp);
  fclose(dest_fp);
  free(buf.buf);
}

void genHeader(arena * a)
{
  char * suffix = ".h";
  size_t suffix_len = strlen(suffix);

  size_t name_len = strlen(a->name);
  char filename[FILE_NAME_SIZE];

  if (suffix_len + name_len > FILE_NAME_SIZE)
  {
    printf("File name of %s is too long. Max file name size is %zu. Exiting\n",
           a->name,
           FILE_NAME_SIZE - suffix_len);
    exit(EXIT_FAILURE);
  }

  strcpy(filename, a->name);
  strcat(filename, suffix);

  #define HEADER_SOURCE_FILE ASSET_DIR "header.txt" 
  FILE * source_fp = fopen(HEADER_SOURCE_FILE, "r");
  assert(source_fp);
  FILE * dest_fp = fopen(filename, "w");
  assert(dest_fp);

  buffer buf;
  buf.buf_size = BUF_SIZE;
  buf.buf = calloc(1, BUF_SIZE);
  copyFileToBuf(&buf, source_fp);
  char caps_filename[FILE_NAME_SIZE];
  strcpy(caps_filename, a->name);
  strtoupper(caps_filename);
  fprintf(dest_fp, buf.buf, 
          caps_filename, 
          caps_filename);
  fclose(source_fp);
  fclose(dest_fp);
  free(buf.buf);
}

int main(int argc, char ** argv)
{
  arena a = {0};
  parseCLI(&a, argc, argv);
  validateProjectName(&a);
  genCFile(&a);
  genHeader(&a);
}
